//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooCandle
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandleComposition
    {
        public int Id { get; set; }
        public int CandleId { get; set; }
        public int MaterialId { get; set; }
    
        public virtual Candle Candle { get; set; }
        public virtual Material Material { get; set; }
    }
}
